//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

interface IColor
{
	id: string;
	name: string;
}
interface IImage
{
	id: string;
	url: string;
}
interface IProduct
{
	id: string;
	count: number;
	collection: string;
	category: string;
	labelName: string;
	brand: string;
	price: number;
	salePrice: number;
	images: IImage[];
	weight: number;
	colors: IColor[];
	metal: string;
	sizes: ISize[];
	description: string;
	popularity: number;
	customPopularity: number;
}
interface ISize
{
	id: string;
	value: number;
}
interface IOrder
{
	products: IOrderedProduct[];
	phone: string;
	contactType: string;
}
interface IOrderedProduct extends IProduct
{
	size: number;
	color: string;
}
