//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

interface IProduct
{
	id: string;
	count: number;
	collection: string;
	category: string;
	labelName: string;
	brand: string;
	price: number;
	salePrice: number;
	image: string;
	weight: number;
	color: string;
	metal: string;
	size: number;
	description: string;
	popularity: number;
	customPopularity: number;
}
